### ISSUE TITLE
cat not set "lagom-version"

### ISSUE THREAD

**Issue by lupingqiu** [lagom/lagom-scala.g8#78]
I followed this document 👍 https://www.lagomframework.com/documentation/1.6.x/java/GettingStartedSbt.html,
and I can't set lagom-version. How to fix it?

**Comment by octonato** [comment]
I think the page is out of date. It is still pointing to Lagom 1.3.2 for instance. 

I will remove that part from the docs, I think we removed it because we want people to start on the latest release. It doesn't make sense to start a new project on a previous Lagom version.

Anyway, the template will create a Lagom app using the latest version (v1.6.1). If you want to downgrade it, you can edit `project/plugins.sbt`.

**Comment by octonato** [comment]
I'm closing this as it will be solved in https://github.com/lagom/lagom/pull/2763

**Comment by renatocaval** [comment]
@Mergifyio backport 1.5.x
